controllers:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 100
  robot_state_controller:
    type: robot_state_controller/RobotStateController
    publish_rate: 200

  trigger_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ trigger_joint_motor ]
    velocity:
      search_velocity: 4.0
      vel_threshold: 0.001
      joint: trigger_joint
      pid: { p: 1.2, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  scope_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ scope_joint_motor ]
    velocity:
      search_velocity: -3.1415
      vel_threshold: 0.001
      joint: scope_joint
      pid: { p: 0.24, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  image_transmission_calibration_controller:
    type: rm_calibration_controllers/MechanicalCalibrationController
    actuator: [ image_transmission_joint_motor ]
    velocity:
      search_velocity: 12.56
      vel_threshold: 0.001
      joint: image_transmission_joint
      pid: { p: 0.006, i: 0, d: 0.0, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true }

  chassis_controller:
    type: rm_chassis_controllers/OmniController
    # ChassisBase
    publish_rate: 100
    enable_odom_tf: true
    publish_odom_tf: true
    enable_map_tf: true
    power:
      effort_coeff: 2.30
      vel_coeff: 0.012
      power_offset: -9.8
    twist_angular: 0.5233
    max_odom_vel: 10.0
    timeout: 0.1
    pid_follow: { p: 8.0, i: 0, d: 0.02, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
    twist_covariance_diagonal: [ 0.001, 0.001, 0.001, 0.001, 0.001, 0.001 ]

    # OmniController
    wheels:
      left_front:
        pose: [ 0.219, 0.215, 0. ]
        roller_angle: -0.785
        joint: left_front_wheel_joint
        <<: &wheel_setting
          radius: 0.07625
          pid: { p: 0.6, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
      right_front:
        pose: [ 0.219, -0.215, 0. ]
        roller_angle: 0.785
        joint: right_front_wheel_joint
        <<: *wheel_setting
      left_back:
        pose: [ -0.219, 0.215, 0. ]
        roller_angle: 0.785
        joint: left_back_wheel_joint
        <<: *wheel_setting
      right_back:
        pose: [ -0.219, -0.215, 0. ]
        roller_angle: -0.785
        joint: right_back_wheel_joint
        <<: *wheel_setting

  orientation_controller:
    type: rm_orientation_controller/Controller
    publish_rate: 100
    name: "gimbal_imu"
    frame_source: "odom"
    frame_target: "base_link"

  gimbal_controller:
    type: rm_gimbal_controllers/Controller
    controllers:
      yaw:
        joint: "yaw_joint"
        pid: { p: 2.2, i: 25.0, d: 0.0, i_clamp_max: 0.15, i_clamp_min: -0.15, antiwindup: true, publish_state: true }
        pid_pos: { p: 10.0, i: 0.0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
        k_chassis_vel: 0.0
        k_v: 1.0
        accel: 40.0
      pitch:
        joint: "pitch_joint"
        pid: { p: 1.2, i: 18.0, d: 0.0, i_clamp_max: 0.25, i_clamp_min: -0.25, antiwindup: true, publish_state: true }
        pid_pos: { p: 18.0, i: 0, d: 0.0, i_max: 0.0, i_min: 0.0, antiwindup: true, publish_state: true }
        k_v: 1.0
        accel: 40.0
    imu_name: "gimbal_imu"
    feedforward:
      gravity: 0.0
      enable_gravity_compensation: false
      mass_origin: [ 0.0,0.0,0.0 ]
    bullet_solver:
      resistance_coff_qd_10: 0.15
      resistance_coff_qd_15: 0.15
      resistance_coff_qd_16: 0.15
      resistance_coff_qd_18: 0.15
      resistance_coff_qd_30: 0.15
      g: 9.81
      delay: 0.32
      wait_next_armor_delay: 0.08
      wait_diagonal_armor_delay: 0.12
      dt: 0.001
      timeout: 0.001
      publish_rate: 50
      max_switch_angle: 50
      min_switch_angle: 2
      ban_shoot_duration: 0.0
      gimbal_switch_duration: 0.0
      max_track_target_vel: 1.2
    chassis_vel:
      num_data: 20
      debug: true

  shooter_controller:
    type: rm_shooter_controllers/Controller
    publish_rate: 50
    friction:
      friction_left:
        left_front_friction_wheel:
          joint: "left_front_friction_wheel_joint"
          pid: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
        left_back_friction_wheel:
          joint: "left_back_friction_wheel_joint"
          pid: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
          wheel_speed_offset: -75
      friction_mid:
        mid_front_friction_wheel:
          joint: "mid_front_friction_wheel_joint"
          pid: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
          wheel_speed_direction: -1.0
        mid_back_friction_wheel:
          joint: "mid_back_friction_wheel_joint"
          pid: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
          wheel_speed_offset: -75
          wheel_speed_direction: -1.0
      friction_right:
        right_front_friction_wheel:
          joint: "right_front_friction_wheel_joint"
          pid: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
          wheel_speed_direction: -1.0
        right_back_friction_wheel:
          joint: "right_back_friction_wheel_joint"
          pid: { p: 0.001, i: 0.01, d: 0.0, i_clamp_max: 0.01, i_clamp_min: -0.01, antiwindup: true, publish_state: true }
          wheel_speed_offset: -75
          wheel_speed_direction: -1.0
    trigger:
      joint: "trigger_joint"
      pid: { p: 28.0, i: 0.0, d: 0.85, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
    push_per_rotation: 6
    push_qd_threshold: 0.85
    block_effort: 6.8
    block_speed: 0.1
    block_duration: 0.05
    block_overtime: 0.5
    anti_block_angle: 0.43
    anti_block_threshold: 0.1
    forward_push_threshold: 0.2
    exit_push_threshold: 0.23
    offset: 220.0
