can_motors:
  ############ can0 ############
  - can_id: 1
    can_bus: 0
    name: "small_joint1_motor"
    type: "DM4310"
    need_calibration: false
  - can_id: 2
    can_bus: 0
    name: "small_joint2_motor"
    type: "DM4310"
    need_calibration: false
  - can_id: 3
    can_bus: 0
    name: "small_joint3_motor"
    type: "DM4310"
    need_calibration: false
