rm_manual:
  robot_type: "legged_wheel_balance"
  dbus_topic: "/rm_ecat_hw/dbus"
  chassis_calibrate_motor: [ "left_front_leg_joint_motor", "right_front_leg_joint_motor", "left_back_leg_joint_motor", "right_back_leg_joint_motor" ]
  gimbal_calibrate_motor: [ "pitch_joint_motor" ]
  shooter_calibrate_motor: [ ]
  supply_frame: "yaw"
  chassis:
    topic: "/cmd_chassis"
    accel_x:
      - [ 60.0,1.0 ]
      - [ 80.0,1.3 ]
      - [ 100.0,1.5 ]
      - [ 220.0,2.0 ]
    accel_y:
      - [ 60.0,2.0 ]
    accel_z:
      - [ 60.0,4.8 ]
      - [ 80.0,5.0 ]
      - [ 100.0,7.0 ]
      - [ 150.0,8.0 ]
    safety_power: 30
    capacitor_threshold: 0.2
    charge_power: 40
    extra_power: 60
    burst_power: 280
    buffer_threshold: 10
    minimum_power: 40
    power_gain: 0.9
    is_new_capacitor: true
  balance:
    flank_frame: "flank_frame"
    reverse_frame: "yaw_reverse_frame"
    legged_wheel_chassis:
      topic: "/leg_cmd"
      unstick_topic: "/controllers/legged_balance_controller/unstick/two_leg_unstick"
  vel:
    topic: "/cmd_vel"
    power_limit_topic: "/cmd_chassis"
    max_linear_x:
      - [ 60.0,1.20 ]
      - [ 80.0,1.30 ]
      - [ 180.0,1.80 ]
      - [ 280.0,2.00 ]
    max_linear_y:
      - [ 60.0,1.20 ]
      - [ 80.0,1.30 ]
      - [ 100.0,1.40 ]
      - [ 280.0,1.50 ]
    max_angular_z:
      - [ 60.0,9.3 ]
      - [ 80.0,9.4 ]
      - [ 280.0,9.5 ]
    gyro_move_reduction: 0.5
    gyro_rotate_reduction: 1.0
  gimbal:
    topic: "/controllers/gimbal_controller/command"
    max_yaw_vel: 12.56
    max_pitch_vel: 8.37
    gimbal_scale: 8
    track_timeout: 0.5
    finish_turning_threshold: 2.9
    target_cost_function:
      k_pos: 1.0
      k_vel: 1.0
      k_hp: 1.0
      k_freq: 1.0
      timeout: 0.05
  shooter:
    topic: "/controllers/shooter_controller/command"
    track_armor_error_tolerance: 0.08
    untrack_armor_error_tolerance: 0.04
    max_track_target_vel: 10.8
    track_buff_error_tolerance: 0.12
    target_acceleration_tolerance: 99.0
    speed_10m_per_speed: 23.5
    speed_15m_per_speed: 23.5
    speed_16m_per_speed: 23.5
    speed_18m_per_speed: 23.5
    speed_30m_per_speed: 23.5
    wheel_speed_15: 715.0
    wheel_speed_18: 715.0
    wheel_speed_30: 715.0
    extra_wheel_speed_once: 5.0
    heat_limit:
      low_shoot_frequency: 20
      high_shoot_frequency: 20
      burst_shoot_frequency: 20
      minimal_shoot_frequency: 1.75
      safe_shoot_frequency: 3
      safe_speed_limit: 30
      heat_coeff: 10.0
      is_local: true
      type: "ID1_17MM"
  cover:
    topic: "/controllers/cover_controller/command"
    on_pos: -1.460
    off_pos: -0.02
  detection_switch:
    fail_limit: 10
    service_name: "/Processor/status_switch"
  buff_switch:
    fail_limit: 10
    service_name: "/buff_status_switch"
  buff_type_switch:
    fail_limit: 10
    service_name: "/forecast/status_switch"
  exposure_switch:
    fail_limit: 10
    service_name: "/exposure_status_switch"

  controllers_list:
    state_controllers:
      - controllers/joint_state_controller
      - controllers/robot_state_controller
    main_controllers:
      - controllers/orientation_controller
      - controllers/legged_balance_controller
      - controllers/gimbal_controller
      - controllers/shooter_controller
    calibration_controllers:
      - controllers/leg_lf_calibration_controller
      - controllers/leg_lb_calibration_controller
      - controllers/leg_rf_calibration_controller
      - controllers/leg_rb_calibration_controller
      - controllers/gimbal_calibration_controller
      - controllers/trigger_calibration_controller

  chassis_calibration:
    - start_controllers:
        - controllers/leg_lf_calibration_controller
        - controllers/leg_lb_calibration_controller
        - controllers/leg_rf_calibration_controller
        - controllers/leg_rb_calibration_controller
      stop_controllers:
        - ""
      services_name:
        - /controllers/leg_lf_calibration_controller/is_calibrated
        - /controllers/leg_lb_calibration_controller/is_calibrated
        - /controllers/leg_rf_calibration_controller/is_calibrated
        - /controllers/leg_rb_calibration_controller/is_calibrated
  gimbal_calibration:
    - start_controllers:
        - controllers/gimbal_calibration_controller
      stop_controllers:
        - controllers/gimbal_controller
      services_name:
        - /controllers/gimbal_calibration_controller/is_calibrated
  shooter_calibration:
    - start_controllers:
        - controllers/trigger_calibration_controller
      stop_controllers:
        - controllers/shooter_controller
      services_name:
        - /controllers/trigger_calibration_controller/is_calibrated

#controllers:
#  cover_controller:
#    type: effort_controllers/JointPositionController
#    joint: "cover_joint"
#    pid: { p: 7.0, i: 0.0, d: 0.5, i_clamp_max: 0.0, i_clamp_min: 0.0, antiwindup: true, publish_state: true }
